const songs = [
  {
    id: "1",
    title: "KICK BACK",
    artist: "Kenshi Yonezu",
    file: require("../assets/songs/CHAINSAW MAN  Opening - KICK BACK.mp3"),
    artwork: require("../assets/artwork/kick_back.jpg"),
    color: ["#E8251A", "#5C0A08"],
  },
  {
    id: "2",
    title: "Bocca della Verita",
    artist: "Ado",
    file: require("../assets/songs/【Ado】Bocca della Verita.mp3"),
    artwork: require("../assets/artwork/Bocca della Verita.jpg"),
    color: ["#7B35CC", "#1A0845"],
  },
  {
    id: "3",
    title: "Usseewa",
    artist: "Ado",
    file: require("../assets/songs/【Ado】うっせぇわ (Usseewa).mp3"),
    artwork: require("../assets/artwork/Usseewa.png"),
    color: ["#2A3AE8", "#080A3D"],
  },
  {
    id: "4",
    title: "Ezio's Family",
    artist: "Jesper Kyd",
    file: require("../assets/songs/Assassin's Creed 2 OST _ Jesper Kyd - Ezio's Family.mp3"),
    artwork: require("../assets/artwork/Assassin's Creed 2 OST.jpg"),
    color: ["#8B1A1A", "#2A0808"],
  },
  {
    id: "5",
    title: "Ashes on The Fire",
    artist: "Hiroyuki Sawano",
    file: require("../assets/songs/Attack on Titan Season 4 OST - Ashes on The Fire - Main Theme.mp3"),
    artwork: require("../assets/artwork/aot.jpg"),
    color: ["#D46B1A", "#3D1A05"],
  },
  {
    id: "6",
    title: "Black Catcher",
    artist: "Vickeblanka",
    file: require("../assets/songs/Black Clover Opening 10 _ Black Catcher.mp3"),
    artwork: require("../assets/artwork/Black Catcher.jpg"),
    color: ["#CC2020", "#1A0808"],
  },
  {
    id: "7",
    title: "Clavar La Espada",
    artist: "Bleach OST",
    file: require("../assets/songs/Bleach OST 3-Clavar La Espada.mp3"),
    artwork: require("../assets/artwork/bleach_espada.jpg"),
    color: ["#7A8E9E", "#1A2530"],
  },
  {
    id: "8",
    title: "Asphyxia",
    artist: "Cö shu Nie",
    file: require("../assets/songs/Cö shu Nie - Asphyxia.mp3"),
    artwork: require("../assets/artwork/asphyxia.jpg"),
    color: ["#9B6B8A", "#1A0A1A"],
  },
  {
    id: "9",
    title: "Bling-Bang-Bang-Born",
    artist: "Creepy Nuts",
    file: require("../assets/songs/Creepy Nuts「Bling-Bang-Bang-Born」×TV Anime「マッシュル-MASHLE-」.mp3"),
    artwork: require("../assets/artwork/Bling-Bang-Bang-Born.jpg"),
    color: ["#D4B800", "#3D3000"],
  },
  {
    id: "10",
    title: "The Rebel Path (Cello Version)",
    artist: "Cyberpunk 2077 OST",
    file: require("../assets/songs/Cyberpunk 2077 OST - The Rebel Path (Cello Version).mp3"),
    artwork: require("../assets/artwork/Cyberpunk 2077 OST - The Rebel Path.jpg"),
    color: ["#D4C800", "#2A2500"],
  },
  {
    id: "11",
    title: "I Really Want to Stay At Your House",
    artist: "Rosa Walton",
    file: require("../assets/songs/Cyberpunk_ Edgerunners _ I Really Want to Stay At Your House by Rosa Walton.mp3"),
    artwork: require("../assets/artwork/Cyberpunk Edgerunners.jpg"),
    color: ["#C8D400", "#252A00"],
  },
  {
    id: "12",
    title: "Otonoke",
    artist: "Creepy Nuts",
    file: require("../assets/songs/DAN DA DAN Opening _ Otonoke by Creepy Nuts.mp3"),
    artwork: require("../assets/artwork/Otonoke.jpg"),
    color: ["#5B30CC", "#180A45"],
  },
  {
    id: "13",
    title: "Kaen",
    artist: "Dororo",
    file: require("../assets/songs/Dororo - Opening 1 - Kaen.mp3"),
    artwork: require("../assets/artwork/dororo.jpg"),
    color: ["#E87820", "#3D1E05"],
  },
  {
    id: "14",
    title: "MIDDLE OF THE NIGHT",
    artist: "Elley Duhé",
    file: require("../assets/songs/Elley Duhé - MIDDLE OF THE NIGHT (Audio).mp3"),
    artwork: require("../assets/artwork/middle_of_the_night.jpg"),
    color: ["#1DB87A", "#063D28"],
  },
  {
    id: "15",
    title: "Feels OST",
    artist: "Lies of P",
    file: require("../assets/songs/feel.mp3"),
    artwork: require("../assets/artwork/feel.jpg"),
    color: ["#1A8BB0", "#052535"],
  },
  {
    id: "16",
    title: "Brothers",
    artist: "Fullmetal Alchemist Brotherhood",
    file: require("../assets/songs/Fullmetal Alchemist_ Brotherhood - Opening 1.mp3"),
    artwork: require("../assets/artwork/the-cast-of-fullmetal-alchemist-brotherhood.jpg"),
    color: ["#C87820", "#3D2005"],
  },
  {
    id: "17",
    title: "Work",
    artist: "Ringo Sheena & Millennium Parade",
    file: require("../assets/songs/Hell's Paradise Opening 1 _ _Work_ by Ringo Sheena and Millennium Parade.mp3"),
    artwork: require("../assets/artwork/Hell's Paradise Opening.jpg"),
    color: ["#E8512A", "#7A1A0A"],
  },
  {
    id: "18",
    title: "Infinity Castle Theme",
    artist: "Demon Slayer OST",
    file: require("../assets/songs/Infinity Castle Theme _ Demon slayer_ S4 E8 OST.mp3"),
    artwork: require("../assets/artwork/Infinity Castle Theme.jpg"),
    color: ["#C97A1A", "#3D1A05"],
  },
  {
    id: "19",
    title: "How I'd Kill",
    artist: "Cowboy Malfoy",
    file: require("../assets/songs/kill.mp3"),
    artwork: require("../assets/artwork/how_id_kill.jpg"),
    color: ["#2E8B6A", "#0D3D2E"],
  },
  {
    id: "20",
    title: "Lumiere",
    artist: "Clair Obscur: Expedition 33",
    file: require("../assets/songs/lumiere.mp3"),
    artwork: require("../assets/artwork/lumiere.jpg"),
    color: ["#C4302A", "#3D0A08"],
  },
  {
    id: "21",
    title: "Paradox",
    artist: "Survive Said The Prophet",
    file: require("../assets/songs/Paradox _ Survive Said The Prophet VINLAND SAGA SEASON 2 Collaboration MV.mp3"),
    artwork: require("../assets/artwork/paradox.jpg"),
    color: ["#D4920A", "#3D2800"],
  },
  {
    id: "22",
    title: "Me And The Devil",
    artist: "Soap&Skin",
    file: require("../assets/songs/Soap&Skin - Me And The Devil.mp3"),
    artwork: require("../assets/artwork/Me And The Devil.jpg"),
    color: ["#8B6B3A", "#1A1005"],
  },
  {
    id: "23",
    title: "LEveL",
    artist: "Hiroyuki Sawano & TOMORROWxTOGETHER",
    file: require("../assets/songs/Solo Leveling Opening LEVEL by Hiroyuki Sawano nZk and TOMORROW X TOGETHER.mp3"),
    artwork: require("../assets/artwork/solo_leveling_level.jpg"),
    color: ["#2A6ECC", "#080F3D"],
  },
  {
    id: "24",
    title: "Arise",
    artist: "LiSA feat Felix of Stray Kids",
    file: require("../assets/songs/Solo Leveling Season 2 -Arise from the Shadow- Opening _ _ReawakeR_ by LiSA feat Felix of Stray Kids.mp3"),
    artwork: require("../assets/artwork/arise.jpg"),
    color: ["#C0389A", "#1A0A3D"],
  },
  {
    id: "25",
    title: "Touch Off",
    artist: "UVERworld",
    file: require("../assets/songs/The Promised Neverland Opening - UVERworld - Touch off.mp3"),
    artwork: require("../assets/artwork/touch_off.jpg"),
    color: ["#D4820A", "#3D2000"],
  },
  {
    id: "26",
    title: "Unravel",
    artist: "TK from Ling Toshite Sigure",
    file: require("../assets/songs/Tokyo Ghoul Opening _ _Unravel_ by TK from Ling Toshite Sigure.mp3"),
    artwork: require("../assets/artwork/unraveljpg.jpg"),
    color: ["#1A7E7A", "#052525"],
  },
  {
    id: "27",
    title: "SPECIALZ",
    artist: "King Gnu",
    file: require("../assets/songs/SPECIAL.mp3"),
    artwork: require("../assets/artwork/special.jpg"),
    color: ["#C45A1A", "#3D1505"],
  },
  {
    id: "28",
    title: "Mukanjyo",
    artist: "Survive Said The Prophet",
    file: require("../assets/songs/VINLAND SAGA Opening 1 _ Mukanjyo by Survive Said the Prophet.mp3"),
    artwork: require("../assets/artwork/Mukanjyo.jpg"),
    color: ["#8B3A2A", "#200A05"],
  },
  {
    id: "29",
    title: "Vogel im Käfig",
    artist: "Hiroyuki Sawano",
    file: require("../assets/songs/Vogel im Käfig.mp3"),
    artwork: require("../assets/artwork/Vogel im Käfig.jpg"),
    color: ["#4A8FCC", "#0A1E35"],
  },
];

export default songs;
